### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by fcebron** [simchanu29/ros_usv_simulator#1]
You need to add inside the "Readme.txt" that this package depends of "ros_maestro" that you've coded.

**Comment by fcebron** [comment]
Same thing for "ros_teleop"

**Comment by simchanu29** [comment]
This package shouldn't be dependent on any other package. The good way would be to separate the core of the simulation and the plugins. 

TODO : 
 - move simulation of ros_maestro inside ros_maestro_simu_plugin and decide if it should be inside the ros_maestro package 
 - add a list of available plugins packages inside readme.md
 - same for teleop

**Comment by simchanu29** [comment]
Issue solved
Release 0.1 published
